export type NeuroConcern =
  // Cognitive
  | "mentalClarity"
  | "memoryPreservation"
  | "concentrationAbility"
  // Mood & Psychiatric
  | "moodStability"
  | "lowAnxiety"
  | "emotionalStability"
  // Physical
  | "weightNeutrality"
  | "hairPreservation"
  | "lowFatigue"
  | "lowDizziness"
  | "lowTremor"
  // Organ Safety
  | "liverSafety"
  | "kidneySafety"
  | "boneSafety"
  // Reproductive
  | "pregnancySafety"
  | "fertilityPreservation"
  // Practical
  | "easyTitration"
  | "lowDrugInteractions"
  | "genericAvailability"
  | "onceDaily"
  // Efficacy
  | "seizureControl"
  | "migraineReduction"
  | "fastOnset"

export interface NeuroConcernInfo {
  id: NeuroConcern
  label: string
  description: string
  category: string
}

export const neuroConcerns: NeuroConcernInfo[] = [
  { id: "mentalClarity", label: "Mental Clarity", description: "Minimize brain fog and word-finding difficulty", category: "Cognitive" },
  { id: "memoryPreservation", label: "Memory Preservation", description: "Avoid short-term memory issues", category: "Cognitive" },
  { id: "concentrationAbility", label: "Concentration", description: "Maintain focus and attention", category: "Cognitive" },
  { id: "moodStability", label: "Mood Stability", description: "No irritability, rage, or depression worsening", category: "Mood & Psychiatric" },
  { id: "lowAnxiety", label: "Low Anxiety Risk", description: "Avoid worsening anxiety", category: "Mood & Psychiatric" },
  { id: "emotionalStability", label: "Emotional Stability", description: "No mood swings or behavioral changes", category: "Mood & Psychiatric" },
  { id: "weightNeutrality", label: "Weight Neutrality", description: "Minimize weight gain or loss", category: "Physical" },
  { id: "hairPreservation", label: "Hair Preservation", description: "Avoid hair loss/thinning", category: "Physical" },
  { id: "lowFatigue", label: "Low Fatigue", description: "Stay alert and energized", category: "Physical" },
  { id: "lowDizziness", label: "Low Dizziness", description: "Minimize vertigo and balance issues", category: "Physical" },
  { id: "lowTremor", label: "Low Tremor", description: "Avoid hand tremor or shakiness", category: "Physical" },
  { id: "liverSafety", label: "Liver Safety", description: "Low hepatotoxicity risk", category: "Organ Safety" },
  { id: "kidneySafety", label: "Kidney Safety", description: "Low nephrotoxicity/stone risk", category: "Organ Safety" },
  { id: "boneSafety", label: "Bone Health", description: "Minimize bone density loss", category: "Organ Safety" },
  { id: "pregnancySafety", label: "Pregnancy Safety", description: "Low teratogenic risk", category: "Reproductive" },
  { id: "fertilityPreservation", label: "Fertility Preservation", description: "No impact on reproductive function", category: "Reproductive" },
  { id: "easyTitration", label: "Easy Titration", description: "Simple dose adjustment schedule", category: "Practical" },
  { id: "lowDrugInteractions", label: "Low Drug Interactions", description: "Fewer conflicts with other meds", category: "Practical" },
  { id: "genericAvailability", label: "Generic Available", description: "Affordable generic option", category: "Practical" },
  { id: "onceDaily", label: "Once Daily Dosing", description: "Convenient dosing schedule", category: "Practical" },
  { id: "seizureControl", label: "Seizure Control", description: "Broad-spectrum seizure efficacy", category: "Efficacy" },
  { id: "migraineReduction", label: "Migraine Prevention", description: "Effective migraine frequency reduction", category: "Efficacy" },
  { id: "fastOnset", label: "Fast Onset", description: "Quick time to therapeutic effect", category: "Efficacy" },
]

export interface NeuroMedication {
  id: string
  name: string
  genericName: string
  brand: string
  class: "Anticonvulsant" | "Beta-Blocker" | "TCA" | "CGRP Inhibitor" | "Calcium Channel Blocker"
  halfLife: string
  halfLifeHours: number
  primaryMechanism: string
  doseRange: string
  availableDoses: string
  timeToEffect: string
  fdaIndications: string[]
  pregnancyRisk: string
  scores: Record<NeuroConcern, number>
  sideEffects: string[]
  clinicalNotes: string
}

export const neuroMedications: NeuroMedication[] = [
  {
    id: "topiramate",
    name: "Topiramate",
    genericName: "topiramate",
    brand: "Topamax",
    class: "Anticonvulsant",
    halfLife: "21 hours",
    halfLifeHours: 21,
    primaryMechanism: "Multiple: sodium channel blockade, GABA enhancement, glutamate antagonism, carbonic anhydrase inhibition",
    doseRange: "25–400 mg/day",
    availableDoses: "25, 50, 100, 200 mg tablets; 15, 25 mg sprinkle capsules",
    timeToEffect: "2–4 weeks (titrate over 6–8 weeks)",
    fdaIndications: ["Epilepsy (partial-onset, primary generalized tonic-clonic)", "Migraine prevention"],
    pregnancyRisk: "Category D — oral clefts risk",
    scores: {
      mentalClarity: 20, memoryPreservation: 25, concentrationAbility: 30,
      moodStability: 55, lowAnxiety: 60, emotionalStability: 50,
      weightNeutrality: 85, hairPreservation: 75, lowFatigue: 55, lowDizziness: 50, lowTremor: 70,
      liverSafety: 75, kidneySafety: 40, boneSafety: 60,
      pregnancySafety: 25, fertilityPreservation: 60,
      easyTitration: 35, lowDrugInteractions: 55, genericAvailability: 95, onceDaily: 50,
      seizureControl: 75, migraineReduction: 85, fastOnset: 40,
    },
    sideEffects: ["Cognitive dulling", "Word-finding difficulty", "Paresthesias", "Kidney stones", "Weight loss", "Metabolic acidosis", "Taste perversion"],
    clinicalNotes: "\"Dopamax\" nickname due to severe cognitive dulling. Word-finding difficulty is hallmark side effect. Kidney stones in 1-5%. Weight loss is common. Carbonic anhydrase inhibition. Effective for both seizures and migraines. Paresthesias (tingling) are very common but usually benign.",
  },
  {
    id: "valproate",
    name: "Valproate/Divalproex",
    genericName: "valproic acid/divalproex sodium",
    brand: "Depakote",
    class: "Anticonvulsant",
    halfLife: "9–16 hours",
    halfLifeHours: 12,
    primaryMechanism: "Multiple: GABA enhancement, sodium channel blockade, T-type calcium channel blockade, histone deacetylase inhibition",
    doseRange: "500–2000 mg/day",
    availableDoses: "125, 250, 500 mg DR tablets; 250, 500 mg ER tablets; 125 mg sprinkle capsules; 250 mg/5 mL syrup",
    timeToEffect: "1–2 weeks (with loading), 2–4 weeks standard",
    fdaIndications: ["Epilepsy (complex partial, absence, multiple seizure types)", "Migraine prevention", "Bipolar mania"],
    pregnancyRisk: "Category X — neural tube defects, neurodevelopmental effects",
    scores: {
      mentalClarity: 60, memoryPreservation: 55, concentrationAbility: 55,
      moodStability: 80, lowAnxiety: 70, emotionalStability: 75,
      weightNeutrality: 30, hairPreservation: 35, lowFatigue: 50, lowDizziness: 60, lowTremor: 40,
      liverSafety: 40, kidneySafety: 75, boneSafety: 55,
      pregnancySafety: 5, fertilityPreservation: 40,
      easyTitration: 65, lowDrugInteractions: 40, genericAvailability: 95, onceDaily: 60,
      seizureControl: 90, migraineReduction: 75, fastOnset: 65,
    },
    sideEffects: ["Weight gain", "Hair loss/thinning", "Tremor", "Hepatotoxicity", "Thrombocytopenia", "Pancreatitis", "Teratogenicity"],
    clinicalNotes: "Broadest spectrum anticonvulsant. Category X — neural tube defects in 1-2% of exposed pregnancies, reduced IQ in offspring. Weight gain, hair loss, tremor common. Hepatotoxicity risk especially in children under 2. Monitor levels, LFTs, CBC. Polycystic ovarian syndrome association in young women.",
  },
  {
    id: "lamotrigine",
    name: "Lamotrigine",
    genericName: "lamotrigine",
    brand: "Lamictal",
    class: "Anticonvulsant",
    halfLife: "25 hours",
    halfLifeHours: 25,
    primaryMechanism: "Sodium channel blockade, glutamate release inhibition",
    doseRange: "100–400 mg/day",
    availableDoses: "25, 100, 150, 200 mg tablets; 2, 5, 25 mg chewable tablets; 25, 50, 100, 200 mg ODT; XR 25-300 mg",
    timeToEffect: "4–8 weeks (due to slow titration requirement)",
    fdaIndications: ["Epilepsy (partial-onset, primary generalized tonic-clonic, Lennox-Gastaut)", "Bipolar I maintenance"],
    pregnancyRisk: "Relatively safer — registry data shows lower malformation rate vs other AEDs",
    scores: {
      mentalClarity: 85, memoryPreservation: 82, concentrationAbility: 80,
      moodStability: 85, lowAnxiety: 72, emotionalStability: 80,
      weightNeutrality: 90, hairPreservation: 88, lowFatigue: 80, lowDizziness: 65, lowTremor: 78,
      liverSafety: 80, kidneySafety: 85, boneSafety: 80,
      pregnancySafety: 72, fertilityPreservation: 82,
      easyTitration: 15, lowDrugInteractions: 55, genericAvailability: 95, onceDaily: 60,
      seizureControl: 72, migraineReduction: 45, fastOnset: 20,
    },
    sideEffects: ["Rash (Stevens-Johnson syndrome risk)", "Dizziness", "Headache", "Diplopia", "Nausea", "Insomnia"],
    clinicalNotes: "Best cognitive profile of any anticonvulsant. Mood stabilizing — FDA-approved for bipolar maintenance. Requires very slow titration due to Stevens-Johnson syndrome risk (1 in 1000 in adults, higher in children). Weight neutral. Relatively safer in pregnancy vs other AEDs. Levels affected by estrogen (decrease in pregnancy, fluctuate with OCP). Valproate doubles levels — requires halved dosing.",
  },
  {
    id: "levetiracetam",
    name: "Levetiracetam",
    genericName: "levetiracetam",
    brand: "Keppra",
    class: "Anticonvulsant",
    halfLife: "6–8 hours",
    halfLifeHours: 7,
    primaryMechanism: "SV2A synaptic vesicle protein binding, modulation of neurotransmitter release",
    doseRange: "500–3000 mg/day",
    availableDoses: "250, 500, 750, 1000 mg tablets; 500, 750 mg XR tablets; 100 mg/mL oral solution; IV formulation",
    timeToEffect: "Days to 1–2 weeks (no titration needed)",
    fdaIndications: ["Epilepsy (partial-onset, myoclonic, primary generalized tonic-clonic)"],
    pregnancyRisk: "Relatively safer — registry data favorable",
    scores: {
      mentalClarity: 70, memoryPreservation: 68, concentrationAbility: 65,
      moodStability: 35, lowAnxiety: 40, emotionalStability: 30,
      weightNeutrality: 82, hairPreservation: 85, lowFatigue: 60, lowDizziness: 60, lowTremor: 75,
      liverSafety: 90, kidneySafety: 80, boneSafety: 85,
      pregnancySafety: 70, fertilityPreservation: 80,
      easyTitration: 90, lowDrugInteractions: 95, genericAvailability: 95, onceDaily: 45,
      seizureControl: 80, migraineReduction: 35, fastOnset: 85,
    },
    sideEffects: ["Irritability/aggression (Keppra rage)", "Behavioral changes", "Somnolence", "Dizziness", "Depression", "Anxiety"],
    clinicalNotes: "\"Keppra rage\" — irritability and behavioral changes in 10-15%. No titration needed — can start at therapeutic dose. No drug interactions (renally cleared). Fast onset. Good cognitive profile otherwise. XR formulation allows once-daily dosing. IV available for acute situations. Pyridoxine (B6) supplementation may reduce behavioral side effects.",
  },
  {
    id: "carbamazepine",
    name: "Carbamazepine",
    genericName: "carbamazepine",
    brand: "Tegretol",
    class: "Anticonvulsant",
    halfLife: "12–17 hours (after autoinduction)",
    halfLifeHours: 14,
    primaryMechanism: "Sodium channel blockade (use-dependent), potentiation of GABA",
    doseRange: "400–1600 mg/day",
    availableDoses: "100, 200 mg chewable tablets; 200 mg tablets; 100, 200, 400 mg XR tablets; 100 mg/5 mL suspension",
    timeToEffect: "1–2 weeks",
    fdaIndications: ["Epilepsy (partial-onset, generalized tonic-clonic, mixed)", "Trigeminal neuralgia", "Bipolar disorder"],
    pregnancyRisk: "Category D — neural tube defects, craniofacial defects",
    scores: {
      mentalClarity: 55, memoryPreservation: 55, concentrationAbility: 55,
      moodStability: 70, lowAnxiety: 65, emotionalStability: 68,
      weightNeutrality: 55, hairPreservation: 70, lowFatigue: 50, lowDizziness: 45, lowTremor: 65,
      liverSafety: 50, kidneySafety: 70, boneSafety: 45,
      pregnancySafety: 30, fertilityPreservation: 55,
      easyTitration: 40, lowDrugInteractions: 15, genericAvailability: 95, onceDaily: 45,
      seizureControl: 80, migraineReduction: 40, fastOnset: 55,
    },
    sideEffects: ["Dizziness", "Diplopia", "Ataxia", "Nausea", "Hyponatremia", "Aplastic anemia (rare)", "Stevens-Johnson syndrome", "Drug interactions"],
    clinicalNotes: "Potent CYP3A4 inducer — massive drug interactions. Autoinduction of own metabolism requires dose adjustments over first month. HLA-B*1502 testing required (Asian populations) for SJS risk. Aplastic anemia risk (rare). Effective for focal seizures and trigeminal neuralgia. Monitor levels, CBC, sodium, LFTs.",
  },
  {
    id: "oxcarbazepine",
    name: "Oxcarbazepine",
    genericName: "oxcarbazepine",
    brand: "Trileptal",
    class: "Anticonvulsant",
    halfLife: "9 hours (active metabolite MHD)",
    halfLifeHours: 9,
    primaryMechanism: "Sodium channel blockade, modulation of calcium channels",
    doseRange: "600–2400 mg/day",
    availableDoses: "150, 300, 600 mg tablets; 300 mg/5 mL suspension; 150, 300, 600 mg XR tablets",
    timeToEffect: "1–2 weeks",
    fdaIndications: ["Epilepsy (partial-onset seizures)"],
    pregnancyRisk: "Category C — limited data, potential risk",
    scores: {
      mentalClarity: 62, memoryPreservation: 60, concentrationAbility: 60,
      moodStability: 65, lowAnxiety: 62, emotionalStability: 65,
      weightNeutrality: 68, hairPreservation: 75, lowFatigue: 55, lowDizziness: 40, lowTremor: 68,
      liverSafety: 72, kidneySafety: 70, boneSafety: 55,
      pregnancySafety: 50, fertilityPreservation: 60,
      easyTitration: 55, lowDrugInteractions: 45, genericAvailability: 90, onceDaily: 45,
      seizureControl: 72, migraineReduction: 40, fastOnset: 55,
    },
    sideEffects: ["Dizziness", "Somnolence", "Diplopia", "Hyponatremia", "Nausea", "Headache", "Ataxia"],
    clinicalNotes: "Cleaner version of carbamazepine with fewer drug interactions. Hyponatremia risk (monitor sodium) — occurs in 2-3% of patients. Less enzyme induction than carbamazepine. Still some cross-reactivity with CBZ allergy (25-30%). XR formulation allows BID dosing. Effective for focal seizures.",
  },
  {
    id: "gabapentin",
    name: "Gabapentin",
    genericName: "gabapentin",
    brand: "Neurontin",
    class: "Anticonvulsant",
    halfLife: "5–7 hours",
    halfLifeHours: 6,
    primaryMechanism: "Alpha-2-delta calcium channel subunit binding, modulation of calcium currents",
    doseRange: "900–3600 mg/day",
    availableDoses: "100, 300, 400, 600, 800 mg capsules/tablets; 250 mg/5 mL oral solution; 300, 600 mg Gralise (once-daily)",
    timeToEffect: "1–2 weeks",
    fdaIndications: ["Epilepsy (partial-onset, adjunctive)", "Postherpetic neuralgia"],
    pregnancyRisk: "Category C — limited human data",
    scores: {
      mentalClarity: 55, memoryPreservation: 58, concentrationAbility: 55,
      moodStability: 68, lowAnxiety: 75, emotionalStability: 70,
      weightNeutrality: 55, hairPreservation: 85, lowFatigue: 45, lowDizziness: 45, lowTremor: 70,
      liverSafety: 90, kidneySafety: 72, boneSafety: 78,
      pregnancySafety: 65, fertilityPreservation: 78,
      easyTitration: 75, lowDrugInteractions: 90, genericAvailability: 95, onceDaily: 25,
      seizureControl: 45, migraineReduction: 50, fastOnset: 55,
    },
    sideEffects: ["Somnolence", "Dizziness", "Ataxia", "Fatigue", "Peripheral edema", "Weight gain"],
    clinicalNotes: "Adjunctive only for seizures — not effective as monotherapy. Good for neuropathic pain and anxiety. No drug interactions (renally cleared, no hepatic metabolism). Sedating. TID dosing is inconvenient. Saturable absorption limits bioavailability at high doses (ceiling effect above 1800mg/day). Gralise formulation allows once-daily for PHN.",
  },
  {
    id: "pregabalin",
    name: "Pregabalin",
    genericName: "pregabalin",
    brand: "Lyrica",
    class: "Anticonvulsant",
    halfLife: "6 hours",
    halfLifeHours: 6,
    primaryMechanism: "Alpha-2-delta calcium channel subunit binding (higher affinity than gabapentin), modulation of calcium currents",
    doseRange: "150–600 mg/day",
    availableDoses: "25, 50, 75, 100, 150, 200, 225, 300 mg capsules; 20 mg/mL oral solution",
    timeToEffect: "1 week",
    fdaIndications: ["Epilepsy (partial-onset, adjunctive)", "Fibromyalgia", "Diabetic neuropathy", "Postherpetic neuralgia", "Spinal cord injury neuropathic pain"],
    pregnancyRisk: "Category C — animal studies show risk",
    scores: {
      mentalClarity: 55, memoryPreservation: 55, concentrationAbility: 52,
      moodStability: 68, lowAnxiety: 80, emotionalStability: 70,
      weightNeutrality: 40, hairPreservation: 82, lowFatigue: 40, lowDizziness: 40, lowTremor: 72,
      liverSafety: 88, kidneySafety: 70, boneSafety: 78,
      pregnancySafety: 55, fertilityPreservation: 65,
      easyTitration: 72, lowDrugInteractions: 90, genericAvailability: 75, onceDaily: 45,
      seizureControl: 40, migraineReduction: 45, fastOnset: 70,
    },
    sideEffects: ["Dizziness", "Somnolence", "Weight gain", "Peripheral edema", "Blurred vision", "Dry mouth", "Euphoria"],
    clinicalNotes: "Better bioavailability than gabapentin (linear absorption — no ceiling effect). BID dosing. Weight gain common (5-10% of patients gain >7% body weight). Sedation and dizziness dose-dependent. Schedule V controlled substance (abuse potential — euphoria reported). Good for anxiety (approved for GAD in Europe). Faster onset than gabapentin.",
  },
  {
    id: "zonisamide",
    name: "Zonisamide",
    genericName: "zonisamide",
    brand: "Zonegran",
    class: "Anticonvulsant",
    halfLife: "63 hours",
    halfLifeHours: 63,
    primaryMechanism: "Sodium and T-type calcium channel blockade, carbonic anhydrase inhibition, weak dopamine/serotonin modulation",
    doseRange: "100–600 mg/day",
    availableDoses: "25, 50, 100 mg capsules",
    timeToEffect: "2–4 weeks",
    fdaIndications: ["Epilepsy (partial-onset, adjunctive)"],
    pregnancyRisk: "Category C — animal teratogenicity",
    scores: {
      mentalClarity: 45, memoryPreservation: 48, concentrationAbility: 48,
      moodStability: 60, lowAnxiety: 55, emotionalStability: 58,
      weightNeutrality: 80, hairPreservation: 72, lowFatigue: 50, lowDizziness: 55, lowTremor: 68,
      liverSafety: 72, kidneySafety: 45, boneSafety: 65,
      pregnancySafety: 45, fertilityPreservation: 60,
      easyTitration: 60, lowDrugInteractions: 65, genericAvailability: 90, onceDaily: 90,
      seizureControl: 70, migraineReduction: 55, fastOnset: 35,
    },
    sideEffects: ["Somnolence", "Anorexia", "Dizziness", "Kidney stones", "Cognitive impairment", "Oligohidrosis (reduced sweating)", "Metabolic acidosis"],
    clinicalNotes: "Long half-life allows once-daily dosing. Sulfonamide — avoid in sulfa allergy. Kidney stones similar to topiramate (carbonic anhydrase inhibition). Cognitive effects less severe than topiramate but still present. Weight loss common. Oligohidrosis risk especially in children (heat stroke risk). Can be used as adjunct or monotherapy.",
  },
  {
    id: "lacosamide",
    name: "Lacosamide",
    genericName: "lacosamide",
    brand: "Vimpat",
    class: "Anticonvulsant",
    halfLife: "13 hours",
    halfLifeHours: 13,
    primaryMechanism: "Selective enhancement of slow inactivation of voltage-gated sodium channels, CRMP-2 binding",
    doseRange: "200–400 mg/day",
    availableDoses: "50, 100, 150, 200 mg tablets; 10 mg/mL oral solution; 10 mg/mL IV solution",
    timeToEffect: "1–2 weeks",
    fdaIndications: ["Epilepsy (partial-onset seizures, monotherapy and adjunctive)"],
    pregnancyRisk: "Category C — limited human data",
    scores: {
      mentalClarity: 78, memoryPreservation: 75, concentrationAbility: 75,
      moodStability: 75, lowAnxiety: 70, emotionalStability: 72,
      weightNeutrality: 82, hairPreservation: 85, lowFatigue: 68, lowDizziness: 50, lowTremor: 75,
      liverSafety: 78, kidneySafety: 82, boneSafety: 80,
      pregnancySafety: 55, fertilityPreservation: 75,
      easyTitration: 80, lowDrugInteractions: 80, genericAvailability: 55, onceDaily: 50,
      seizureControl: 65, migraineReduction: 30, fastOnset: 65,
    },
    sideEffects: ["Dizziness", "Headache", "Nausea", "Diplopia", "PR interval prolongation", "Ataxia"],
    clinicalNotes: "Well-tolerated with good cognitive profile. BID dosing. IV formulation available for acute situations. PR prolongation — ECG monitoring recommended, avoid in cardiac conduction disorders. Only for focal seizures (not broad-spectrum). Relatively new with less long-term data. Unique mechanism (slow sodium channel inactivation) complements other AEDs.",
  },
  {
    id: "propranolol",
    name: "Propranolol",
    genericName: "propranolol",
    brand: "Inderal",
    class: "Beta-Blocker",
    halfLife: "3–6 hours (LA: 10 hours effective)",
    halfLifeHours: 5,
    primaryMechanism: "Non-selective beta-adrenergic receptor antagonism (beta-1 and beta-2 blockade)",
    doseRange: "80–240 mg/day",
    availableDoses: "10, 20, 40, 60, 80 mg tablets; 60, 80, 120, 160 mg LA capsules; 20 mg/5 mL solution",
    timeToEffect: "2–4 weeks for migraine prevention",
    fdaIndications: ["Hypertension", "Migraine prevention", "Essential tremor", "Angina", "Hypertrophic cardiomyopathy", "Pheochromocytoma"],
    pregnancyRisk: "Category C — fetal bradycardia and hypoglycemia reported",
    scores: {
      mentalClarity: 80, memoryPreservation: 75, concentrationAbility: 75,
      moodStability: 68, lowAnxiety: 72, emotionalStability: 70,
      weightNeutrality: 65, hairPreservation: 80, lowFatigue: 40, lowDizziness: 60, lowTremor: 90,
      liverSafety: 78, kidneySafety: 85, boneSafety: 85,
      pregnancySafety: 55, fertilityPreservation: 60,
      easyTitration: 72, lowDrugInteractions: 55, genericAvailability: 95, onceDaily: 60,
      seizureControl: 5, migraineReduction: 72, fastOnset: 45,
    },
    sideEffects: ["Fatigue", "Bradycardia", "Hypotension", "Cold extremities", "Bronchospasm", "Depression", "Sexual dysfunction", "Exercise intolerance"],
    clinicalNotes: "First-line migraine preventive with decades of evidence. No cognitive effects — actually reduces performance anxiety. Can worsen asthma (beta-2 blockade), depression, and fatigue. Avoid in diabetes (masks hypoglycemia symptoms). LA formulation allows once-daily dosing. No seizure indication. Excellent for essential tremor. Avoid abrupt discontinuation (rebound hypertension).",
  },
  {
    id: "amitriptyline",
    name: "Amitriptyline",
    genericName: "amitriptyline",
    brand: "Elavil",
    class: "TCA",
    halfLife: "10–50 hours",
    halfLifeHours: 25,
    primaryMechanism: "Serotonin and norepinephrine reuptake inhibition, muscarinic/histaminic/alpha-adrenergic antagonism",
    doseRange: "10–150 mg/day (10–50 mg for migraine prevention)",
    availableDoses: "10, 25, 50, 75, 100, 150 mg tablets",
    timeToEffect: "2–6 weeks",
    fdaIndications: ["Major Depressive Disorder"],
    pregnancyRisk: "Category C — limited data, neonatal effects reported",
    scores: {
      mentalClarity: 45, memoryPreservation: 48, concentrationAbility: 45,
      moodStability: 70, lowAnxiety: 68, emotionalStability: 65,
      weightNeutrality: 30, hairPreservation: 75, lowFatigue: 30, lowDizziness: 45, lowTremor: 72,
      liverSafety: 65, kidneySafety: 80, boneSafety: 75,
      pregnancySafety: 50, fertilityPreservation: 60,
      easyTitration: 70, lowDrugInteractions: 40, genericAvailability: 95, onceDaily: 85,
      seizureControl: 5, migraineReduction: 75, fastOnset: 45,
    },
    sideEffects: ["Sedation", "Weight gain", "Dry mouth", "Constipation", "Urinary retention", "Blurred vision", "Cardiac arrhythmia (overdose)", "Orthostatic hypotension"],
    clinicalNotes: "Effective migraine preventive at low doses (10-50mg). Very sedating — take at bedtime (can be therapeutic for insomnia). Weight gain, dry mouth, constipation from anticholinergic effects. Lowers seizure threshold — avoid in epilepsy. Overdose risk (cardiac toxicity — lethal in overdose). QTc prolongation. Once-daily bedtime dosing. Also useful for tension headache and neuropathic pain.",
  },
  {
    id: "erenumab",
    name: "Erenumab",
    genericName: "erenumab-aooe",
    brand: "Aimovig",
    class: "CGRP Inhibitor",
    halfLife: "28 days",
    halfLifeHours: 672,
    primaryMechanism: "CGRP receptor antagonism (monoclonal antibody targeting CGRP receptor)",
    doseRange: "70–140 mg monthly subcutaneous injection",
    availableDoses: "70 mg/mL, 140 mg/mL autoinjectors",
    timeToEffect: "4–12 weeks (some respond by month 1)",
    fdaIndications: ["Migraine prevention (episodic and chronic)"],
    pregnancyRisk: "No formal category — limited data, long washout period",
    scores: {
      mentalClarity: 92, memoryPreservation: 92, concentrationAbility: 92,
      moodStability: 88, lowAnxiety: 88, emotionalStability: 88,
      weightNeutrality: 90, hairPreservation: 92, lowFatigue: 88, lowDizziness: 88, lowTremor: 92,
      liverSafety: 90, kidneySafety: 90, boneSafety: 90,
      pregnancySafety: 45, fertilityPreservation: 75,
      easyTitration: 90, lowDrugInteractions: 95, genericAvailability: 10, onceDaily: 95,
      seizureControl: 5, migraineReduction: 78, fastOnset: 40,
    },
    sideEffects: ["Constipation", "Injection site reactions", "Muscle spasms", "Hypertension (rare)"],
    clinicalNotes: "Monthly subcutaneous injection. Minimal systemic side effects — highly targeted mechanism. Constipation most common adverse effect. No cognitive effects. Very expensive without insurance ($600+/month). No seizure indication. Relatively new class — limited long-term safety data (approved 2018). Long half-life means effects persist weeks after discontinuation. Hypertension signal in post-marketing data.",
  },
  {
    id: "galcanezumab",
    name: "Galcanezumab",
    genericName: "galcanezumab-gnlm",
    brand: "Emgality",
    class: "CGRP Inhibitor",
    halfLife: "27 days",
    halfLifeHours: 648,
    primaryMechanism: "CGRP ligand binding (monoclonal antibody targeting CGRP peptide directly)",
    doseRange: "120 mg monthly (240 mg loading dose)",
    availableDoses: "120 mg/mL autoinjector, 120 mg/mL prefilled syringe",
    timeToEffect: "1–4 weeks (loading dose accelerates onset)",
    fdaIndications: ["Migraine prevention (episodic and chronic)", "Episodic cluster headache"],
    pregnancyRisk: "No formal category — limited data, long washout period",
    scores: {
      mentalClarity: 92, memoryPreservation: 92, concentrationAbility: 92,
      moodStability: 88, lowAnxiety: 88, emotionalStability: 88,
      weightNeutrality: 92, hairPreservation: 92, lowFatigue: 90, lowDizziness: 90, lowTremor: 92,
      liverSafety: 90, kidneySafety: 90, boneSafety: 90,
      pregnancySafety: 45, fertilityPreservation: 75,
      easyTitration: 92, lowDrugInteractions: 95, genericAvailability: 8, onceDaily: 95,
      seizureControl: 5, migraineReduction: 80, fastOnset: 50,
    },
    sideEffects: ["Injection site reactions", "Injection site pruritus", "Constipation", "Nasopharyngitis", "Antibody development (rare)"],
    clinicalNotes: "Monthly injection. Loading dose (240mg first month) allows faster onset than erenumab. Also approved for episodic cluster headache (unique among CGRP mAbs). Injection site reactions more common than erenumab. Very expensive ($600+/month). Minimal side effect profile. Targets CGRP ligand directly (vs erenumab which targets receptor). Anti-drug antibodies develop in ~5% but rarely affect efficacy.",
  },
  {
    id: "verapamil",
    name: "Verapamil",
    genericName: "verapamil",
    brand: "Calan",
    class: "Calcium Channel Blocker",
    halfLife: "6–8 hours",
    halfLifeHours: 7,
    primaryMechanism: "L-type calcium channel blockade, reduction of intracellular calcium in smooth muscle and cardiac tissue",
    doseRange: "240–480 mg/day (up to 960 mg for cluster headache)",
    availableDoses: "40, 80, 120 mg tablets; 120, 180, 240, 360 mg SR/ER tablets",
    timeToEffect: "1–2 weeks",
    fdaIndications: ["Hypertension", "Angina pectoris", "Supraventricular tachycardia"],
    pregnancyRisk: "Category C — crosses placenta, limited data",
    scores: {
      mentalClarity: 82, memoryPreservation: 80, concentrationAbility: 80,
      moodStability: 78, lowAnxiety: 75, emotionalStability: 78,
      weightNeutrality: 75, hairPreservation: 82, lowFatigue: 65, lowDizziness: 50, lowTremor: 80,
      liverSafety: 72, kidneySafety: 82, boneSafety: 82,
      pregnancySafety: 55, fertilityPreservation: 70,
      easyTitration: 60, lowDrugInteractions: 40, genericAvailability: 95, onceDaily: 35,
      seizureControl: 5, migraineReduction: 45, fastOnset: 55,
    },
    sideEffects: ["Constipation", "Dizziness", "Hypotension", "Bradycardia", "Peripheral edema", "AV block", "Headache"],
    clinicalNotes: "First-line for cluster headache prevention (off-label). ECG monitoring for PR prolongation at high doses (>480mg). Constipation very common. Multiple daily doses needed with IR formulation. Less evidence for migraine than other options. CYP3A4 substrate and inhibitor — drug interactions with statins, digoxin, etc. SR formulation can reduce dosing frequency.",
  },
  {
    id: "brivaracetam",
    name: "Brivaracetam",
    genericName: "brivaracetam",
    brand: "Briviact",
    class: "Anticonvulsant",
    halfLife: "9 hours",
    halfLifeHours: 9,
    primaryMechanism: "High-affinity SV2A synaptic vesicle protein binding (10-30x higher affinity than levetiracetam)",
    doseRange: "50–200 mg/day",
    availableDoses: "10, 25, 50, 75, 100 mg tablets; 10 mg/mL oral solution; 10 mg/mL IV solution",
    timeToEffect: "Days to 1–2 weeks (no titration needed)",
    fdaIndications: ["Epilepsy (partial-onset seizures, adjunctive and monotherapy)"],
    pregnancyRisk: "Category C — limited human data",
    scores: {
      mentalClarity: 80, memoryPreservation: 78, concentrationAbility: 76,
      moodStability: 72, lowAnxiety: 68, emotionalStability: 70,
      weightNeutrality: 82, hairPreservation: 85, lowFatigue: 62, lowDizziness: 58, lowTremor: 75,
      liverSafety: 75, kidneySafety: 82, boneSafety: 82,
      pregnancySafety: 52, fertilityPreservation: 75,
      easyTitration: 85, lowDrugInteractions: 72, genericAvailability: 30, onceDaily: 45,
      seizureControl: 62, migraineReduction: 20, fastOnset: 82,
    },
    sideEffects: ["Somnolence", "Dizziness", "Fatigue", "Nausea", "Irritability (less than levetiracetam)"],
    clinicalNotes: "Related to levetiracetam but with better psychiatric tolerability — less \"rage\" (behavioral AEs in ~5% vs 10-15% with LEV). Higher affinity for SV2A (10-30x). No titration needed. BID dosing. Fewer behavioral side effects than levetiracetam. Relatively expensive — brand only in many markets. IV formulation available. Can be tried in patients intolerant to levetiracetam's psychiatric effects.",
  },
]
